name: flashsculptor
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10.12
  - pip=24.2
  - pytorch=2.4.0
  - torchvision=0.19.0
  - numpy
  - pip:
    - albumentations==0.4.3
    - accelerate
    - diffdist
    - diffusers==0.30.3
    - einops==0.8.0
    - easydict
    - ftfy
    - gsplat==1.0.0
    - huggingface-hub
    - igraph
    - imageio==2.37.0
    - kaolin==0.17.0
    - kornia==0.5.0
    - litellm==1.48.2
    - matplotlib
    - natten==0.14.6
    - omegaconf==2.2.3
    - onnxruntime
    - open3d==0.18.0
    - opencv-python==4.10.0.84
    - pillow==10.4.0
    - plyfile
    - protobuf
    - pydantic==2.9.2
    - pymeshfix
    - pytorch-lightning==1.4.2
    - pyvista
    - rembg
    - scipy==1.10.0
    - sentencepiece
    - timm
    - torchmetrics
    - torchsde==0.2.6
    - tokenizers
    - transformers==4.47.0
    - trimesh
    - triton
    - wandb
    - webdataset
    - xatlas==0.0.9
